package tw.com.andyawd.seenote

class BaseConstants {
    companion object {
        const val TEXT_SIZE = 80
        const val COLOR_SIZE = 120
        const val NOT_FROM_WRITE_NOTE = -1L
        const val NOTE_DATABASE = "note_database"
        const val NOTE_TABLE = "note_table"
        const val SETTING_TABLE = "setting_table"
        const val COLOR_TABLE = "color_table"
        const val DATE_TABLE = "date_table"
        const val USER_TABLE = "user_table"
        const val TEXT_SIZE_TABLE = "text_size_table"
        const val TITLE = "title"
        const val CONTENT = "content"
        const val CREATE_DATE = "create_date"
        const val CREATE = "create"
        const val EDIT_DATE = "edit_date"
        const val EDIT = "edit"
        const val CREATE_NOTE = -1L
        const val EMPTY_STRING = ""
        const val SETTING_SIZE = "setting_size"
        const val BUTTON_TEXT_COLOR = "button_text_color"
        const val BUTTON_BACKGROUND_COLOR = "button_background_color"
        const val PAGE_SIZE = "page_size"
        const val TITLE_TEXT_COLOR = "title_text_color"
        const val TITLE_BACKGROUND_COLOR = "title_background_color"
        const val CONTENT_TEXT_COLOR = "content_text_color"
        const val CONTENT_BACKGROUND_COLOR = "content_background_color"
        const val HORIZONTAL_LINE_COLOR = "horizontal_line_color"
        const val CREATE_DATE_TEXT_COLOR = "create_date_text_color"
        const val CREATE_DATE_BACKGROUND_COLOR = "create_date_background_color"
        const val EDIT_DATE_TEXT_COLOR = "edit_date_text_color"
        const val EDIT_DATE_BACKGROUND_COLOR = "edit_date_background_color"
        const val DATE_TEXT_COLOR = "date_text_color"
        const val DATE_BACKGROUND_COLOR = "date_background_color"
        const val WRITE_SIZE = "write_size"
        const val SELECT_SIZE = "select_size"
        const val LABEL = "label"
        const val TEXT_COLOR = "text_color"
        const val BACKGROUND_COLOR = "background_color"
        const val DATE = "date"
        const val NOTE_PAGE = "note_page"
        const val SELECT_COLOR = "select_color"
        const val SETTING_PAGE = "setting_page"
        const val WRITER_NOTE = "writer_note"
        const val ACCOUNT = "account"
        const val NICKNAME = "nickname"
        const val HACKMD_TOKEN = "hackmd_token"
        const val GOOGLE_TOKEN = "google_token"
        const val OWNER = "owner"
        const val SIGN_IN = "sign_in"
        const val GUEST = "guest"
        const val DISABLED = "disabled"
        const val FORBIDDEN = "forbidden"
        const val SIGNED_IN_USERS = "signed_in_users"
        const val EVERYONE = "everyone"


        const val BLACK = "#000000"
        const val GRAY = "#808080"
        const val SILVER = "#c0c0c0"
        const val GAINSBORO = "#dcdcdc"
        const val WHITE = "#ffffff"
        const val MIDNIGHTBLUE = "#191970"
        const val MEDIUMBLUE = "#0000cd"
        const val DODGERBLUE = "#1e90ff"
        const val SKYBLUE = "#87ceeb"
        const val LIGHTCYAN = "#e0ffff"
        const val DARKGREEN = "#006400"
        const val FORESTGREEN = "#228b22"
        const val LIMEGREEN = "#32cd32"
        const val LIGHTGREEN = "#90ee90"
        const val GREENYELLOW = "#adff2f"
        const val MAROON = "#800000"
        const val FIREBRICK = "#b22222"
        const val RED = "#ff0000"
        const val LIGHTSALMON = "#ffa07a"
        const val PINK = "#ffc0cb"
        const val SADDLEBROWN = "#8b4513"
        const val CHOCOLATE = "#d2691e"
        const val ORANGE = "#ffa500"
        const val GOLD = "#ffd700"
        const val LIGHTYELLOW = "#ffffe0"
        const val DEFAULT = "default"
    }
}